# BERTopic clustering with BGE-M3, UMAP, and HDBSCAN

This notebook mirrors the aggregation pipeline pattern used in the other notebooks, but uses `BAAI/bge-m3` embeddings inside a BERTopic workflow. UMAP reduces the embedding space, HDBSCAN discovers dense event/topic clusters, and `CountVectorizer` uses a trilingual stopword list to suppress boilerplate vocabulary while preserving meaningful Sinhala, Tamil, and English terms.

In [1]:
# Install dependencies when running in a fresh notebook environment.
# Restart the kernel if any package is newly installed.
!pip install -q bertopic sentence-transformers umap-learn hdbscan grapheme
!pip install -U "scipy>=1.15.1"

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.3/207.3 kB 6.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 9.6 MB/s eta 0:00:00
  Building wheel for grapheme (setup.py) ... done
Requirement already satisfied: scipy>=1.15.1 in /usr/local/lib/python3.12/dist-packages (1.16.3)
Collecting scipy>=1.15.1
  Downloading scipy-1.18.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 2.6 MB/s eta 0:00:00
Requirement already satisfied: numpy<2.8,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from scipy>=1.15.1) (2.0.2)
Downloading scipy-1.18.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.3/35.3 MB 57.7 MB/s eta 0:00:00:00:0100:01
Installing collected packages: scipy
  Attempting uninstall: scipy
    Found existing installation: scipy 1.16.3
    Uninstalling scipy-1.16.3:
      Successfully uninstalled scipy-1.16.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ydata-profiling 4.18.4 requires scipy<1.17,>=1.8, but you have scipy 1.18.0 which is incompatible.
Successfully installed scipy-1.18.0

In [2]:
from pathlib import Path
import os
import re
import unicodedata

import numpy as np
import pandas as pd
import grapheme

SEED = 42
np.random.seed(SEED)

NOTEBOOK_DIR = Path.cwd()

# Dataset location
DATA_DIR = Path("/kaggle/input/datasets/uom230425m/aggregation-pipeline-data/data")

# Writable location for results
RESULTS_ROOT = Path("/kaggle/working/results")
RESULTS_DIR = RESULTS_ROOT / "bge_m3_bertopic"

RESULTS_DIR.mkdir(parents=True, exist_ok=True)

print(f"Data dir: {DATA_DIR.resolve()}")
print(f"Results dir: {RESULTS_DIR.resolve()}")

Data dir: /kaggle/input/datasets/uom230425m/aggregation-pipeline-data/data
Results dir: /kaggle/working/results/bge_m3_bertopic

In [3]:
# Load annotator files
df_a = pd.read_csv(DATA_DIR / "a.csv")
df_d = pd.read_csv(DATA_DIR / "d.csv")
df_p = pd.read_csv(DATA_DIR / "p.csv")

for frame in (df_a, df_d, df_p):
    frame.drop(columns=["bias_label"], inplace=True, errors="ignore")

print(df_a.shape, df_d.shape, df_p.shape)

(750, 6) (750, 8) (800, 6)

In [4]:
# Concatenate dataframes and drop duplicate articles by article_id
df = pd.concat([df_a, df_d, df_p], ignore_index=True, sort=False)
df = df.drop_duplicates(subset="article_id", keep="first").reset_index(drop=True)
df.drop(columns=["flags", "Unnamed: 8"], inplace=True, errors="ignore")

print("df shape:", df.shape)
df.head()

df shape: (2000, 6)

,article_id,publisher,url,published_at,title,body_text
0,f92797eb-a338-5886-a45a-66f01292a912,Lanka Deepa,https://www.lankadeepa.lk/news/දන-තර-මර-අහවන-ක...,2025-09-26 00:00:00+00:00,දැන් තෝරු-මෝරු අහුවෙන කාලේ,දැන් තෝරු-මෝරු අහුවෙන කාලේ\n\nදැන් හාල්මැස්සො ...
1,5c7946aa-a810-59e2-a126-ff58347aad21,BBC Sinhala,https://www.bbc.com/sinhala/articles/c0vy04qd14yo,2024-01-17 00:00:00+00:00,අවුරුදු 67යි. ඇස් දෙකම පේන්නේ නෑ. මම පොල් කඩනවා',අවුරුදු 67යි. ඇස් දෙකම පේන්නේ නෑ. මම පොල් කඩනව...
2,6fc575d1-2be5-5d49-be20-c846617bdacd,Ada,https://www.ada.lk/breaking_news/පිදුරංගල-ගිය-...,2026-02-17 00:00:00+00:00,පිදුරංගල ගිය විදේශිකයා වන අලි ප්‍රහාරයෙන් මරුට,පිදුරංගල ගිය විදේශිකයා වන අලි ප්‍රහාරයෙන් මරුට...
3,47965836-064f-530a-a34d-02f6898fb94a,Ada Derana Sinhala,http://sinhala.adaderana.lk/news/194266,2024-03-07 00:00:00+00:00,හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් ගැ...,හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් ගැ...
4,132990f7-a4f4-54ba-8b12-b469d9803bde,Ada Derana Sinhala,http://sinhala.adaderana.lk/news/195779,2024-04-19 00:00:00+00:00,ස්ථාන දෙකකදී ඝාතන දෙකක්,ස්ථාන දෙකකදී ඝාතන දෙකක්\n\nකුලී නිවසක පදිංචිව ...

In [5]:
# Keep rows with the fields required for clustering
required_columns = ["article_id", "publisher", "url", "published_at", "title", "body_text"]
df = df.dropna(subset=required_columns).copy()

print("df shape after required-field dropna:", df.shape)
df.info()

df shape after required-field dropna: (1999, 6)
<class 'pandas.core.frame.DataFrame'>
Index: 1999 entries, 0 to 1999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   article_id    1999 non-null   object
 1   publisher     1999 non-null   object
 2   url           1999 non-null   object
 3   published_at  1999 non-null   object
 4   title         1999 non-null   object
 5   body_text     1999 non-null   object
dtypes: object(6)
memory usage: 109.3+ KB

In [6]:
# Unicode normalization (NFC - canonical decomposition + composition)
for column in ["title", "body_text"]:
    df[column] = df[column].astype(str).map(lambda value: unicodedata.normalize("NFC", value))

df.head()

,article_id,publisher,url,published_at,title,body_text
0,f92797eb-a338-5886-a45a-66f01292a912,Lanka Deepa,https://www.lankadeepa.lk/news/දන-තර-මර-අහවන-ක...,2025-09-26 00:00:00+00:00,දැන් තෝරු-මෝරු අහුවෙන කාලේ,දැන් තෝරු-මෝරු අහුවෙන කාලේ\n\nදැන් හාල්මැස්සො ...
1,5c7946aa-a810-59e2-a126-ff58347aad21,BBC Sinhala,https://www.bbc.com/sinhala/articles/c0vy04qd14yo,2024-01-17 00:00:00+00:00,අවුරුදු 67යි. ඇස් දෙකම පේන්නේ නෑ. මම පොල් කඩනවා',අවුරුදු 67යි. ඇස් දෙකම පේන්නේ නෑ. මම පොල් කඩනව...
2,6fc575d1-2be5-5d49-be20-c846617bdacd,Ada,https://www.ada.lk/breaking_news/පිදුරංගල-ගිය-...,2026-02-17 00:00:00+00:00,පිදුරංගල ගිය විදේශිකයා වන අලි ප්‍රහාරයෙන් මරුට,පිදුරංගල ගිය විදේශිකයා වන අලි ප්‍රහාරයෙන් මරුට...
3,47965836-064f-530a-a34d-02f6898fb94a,Ada Derana Sinhala,http://sinhala.adaderana.lk/news/194266,2024-03-07 00:00:00+00:00,හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් ගැ...,හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් ගැ...
4,132990f7-a4f4-54ba-8b12-b469d9803bde,Ada Derana Sinhala,http://sinhala.adaderana.lk/news/195779,2024-04-19 00:00:00+00:00,ස්ථාන දෙකකදී ඝාතන දෙකක්,ස්ථාන දෙකකදී ඝාතන දෙකක්\n\nකුලී නිවසක පදිංචිව ...

In [7]:
# Remove title duplication from the beginning of the body text
def remove_title_from_body(row):
    body = row["body_text"].strip()
    title = row["title"].strip()
    if body.startswith(title):
        body = body[len(title):].lstrip("\n").lstrip()
    return body


df["text"] = df.apply(remove_title_from_body, axis=1)
df[["title", "text"]].head()

,title,text
0,දැන් තෝරු-මෝරු අහුවෙන කාලේ,දැන් හාල්මැස්සො නොව තෝරු මෝරු අහුවෙන කාලය බවමහ...
1,අවුරුදු 67යි. ඇස් දෙකම පේන්නේ නෑ. මම පොල් කඩනවා',"මෙහි කිසිවක් අඩංගු නැත.Play video, ""දිරිය මිනි..."
2,පිදුරංගල ගිය විදේශිකයා වන අලි ප්‍රහාරයෙන් මරුට,සිගිරිය පිදුරංගල මාර්ගයේදී ඊයේ සවස වන අලියෙකු ...
3,හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් ගැ...,හූති ප්‍රහාරයට ලක්වූ නෞකාවේ සිටි ලාංකිකයින් දෙ...
4,ස්ථාන දෙකකදී ඝාතන දෙකක්,කුලී නිවසක පදිංචිව සිටි පුද්ගලයෙකුව ඊයේ (18) ර...

In [28]:
print(df["text"][10])

2025 රාත්‍රී කාලයේ ගල්නෑව පොලිස් වසමේ බුල්නෑව ප්‍රදේශයේ නිවසක් රුපියල් පන්කෝටි හැත්තැදෙලක්ෂ හැටඅටදහාක් 268 000 වටිනා ප්‍රාඩෝ වර්ගයේ රථයක් භාණ්ඩ මුදල් ජංගම දුරකථන කොල්ලකෑමක් සම්බන්ධයෙන් ගල්නෑව පොලිස් ස්ථානයට පැමිණිල්ලක් විමර්ශන ආරම්භ තිබුණි 2025 ගල්නෑව පොලිස් ස්ථානයේ නිලධාරීන් විසින් ඉහත අපරාධයට සම්බන්ධ සැකකරුවන් හයදෙනෙකු කුරුණෑගල මාතවතගම විල්ගමුව ප්‍රදේශවලදී හෙරොයින් ග්‍රෑම් මිලිග්‍රෑම් 300 අයිස් මත්ද්‍රව්‍ය ග්‍රෑම් මිලිග්‍රෑම් 250 අපරාධයට යොදාගත් අත්වැසුම් අපරාධයට යතුරුපැදියක් රථයක් රථයක් සමඟ අත්අඩංගුවට සැකකරුවන් අවුරුදු වයස්වල පසුවන කුරුණෑගල නුගගොල්ල මාවතගම මැල්සිරිපුර මහනුවර ප්‍රදේශවල පදිංචිකරුවන් සැකකරුවන් විසින් කොල්ලකන ප්‍රාඩෝ වර්ගයේ රථය මීගලෑව ප්‍රදේශයේ තිබියදී සොයාගෙන තවද කොල්ලකන මුදලින් රුපියල් පනස්නමලක්ෂ තිස්නමදාහක 939 000 මුදලක් කොල්ලකන මුදල් වලින් උපයාගන්නා දේපළ රැසක් විමර්ශන නිලධාරීන් භාරයට සැකකරුවන් 2025 කැකිරාව මහේස්ත්‍රාත් අධිකරණයට ඉදිරිපත් වැඩිදුර විමර්ශන සඳහා 2025 දක්වා රැඳවුම් නියෝග ලබාගෙන ගල්නෑව පොලිසිය වැඩිදුර විමර්ශන කරනු ලබයි

In [8]:
import unicodedata

def clean_text(text):
    # Replace punctuation with spaces
    text = "".join(
        " " if unicodedata.category(char).startswith("P") else char
        for char in text
    )

    # Keep words with more than 2 graphemes
    return " ".join(
        word for word in text.split()
        if len(list(grapheme.graphemes(word))) > 2
    )

df["text"] = df["text"].apply(clean_text)

In [25]:
print(df["text"][10])

2025 රාත්‍රී කාලයේ ගල්නෑව පොලිස් වසමේ බුල්නෑව ප්‍රදේශයේ නිවසක් රුපියල් පන්කෝටි හැත්තැදෙලක්ෂ හැටඅටදහාක් 268 000 වටිනා ප්‍රාඩෝ වර්ගයේ රථයක් භාණ්ඩ මුදල් ජංගම දුරකථන කොල්ලකෑමක් සම්බන්ධයෙන් ගල්නෑව පොලිස් ස්ථානයට පැමිණිල්ලක් විමර්ශන ආරම්භ තිබුණි 2025 ගල්නෑව පොලිස් ස්ථානයේ නිලධාරීන් විසින් ඉහත අපරාධයට සම්බන්ධ සැකකරුවන් හයදෙනෙකු කුරුණෑගල මාතවතගම විල්ගමුව ප්‍රදේශවලදී හෙරොයින් ග්‍රෑම් මිලිග්‍රෑම් 300 අයිස් මත්ද්‍රව්‍ය ග්‍රෑම් මිලිග්‍රෑම් 250 අපරාධයට යොදාගත් අත්වැසුම් අපරාධයට යතුරුපැදියක් රථයක් රථයක් සමඟ අත්අඩංගුවට සැකකරුවන් අවුරුදු වයස්වල පසුවන කුරුණෑගල නුගගොල්ල මාවතගම මැල්සිරිපුර මහනුවර ප්‍රදේශවල පදිංචිකරුවන් සැකකරුවන් විසින් කොල්ලකන ප්‍රාඩෝ වර්ගයේ රථය මීගලෑව ප්‍රදේශයේ තිබියදී සොයාගෙන තවද කොල්ලකන මුදලින් රුපියල් පනස්නමලක්ෂ තිස්නමදාහක 939 000 මුදලක් කොල්ලකන මුදල් වලින් උපයාගන්නා දේපළ රැසක් විමර්ශන නිලධාරීන් භාරයට සැකකරුවන් 2025 කැකිරාව මහේස්ත්‍රාත් අධිකරණයට ඉදිරිපත් වැඩිදුර විමර්ශන සඳහා 2025 දක්වා රැඳවුම් නියෝග ලබාගෙන ගල්නෑව පොලිසිය වැඩිදුර විමර්ශන කරනු ලබයි

In [26]:
# Whitespace normalization
df["text"] = df["text"].map(lambda value: re.sub(r"\n{2,}", "\n", value))
df["text"] = df["text"].map(lambda value: re.sub(r"[ \t]+", " ", value))
df["text"] = df["text"].str.strip()

df = df[df["text"].str.len() > 0].reset_index(drop=True)
print("df shape after text cleaning:", df.shape)
df.head()
print(df["text"][10])

df shape after text cleaning: (1999, 10)
2025 රාත්‍රී කාලයේ ගල්නෑව පොලිස් වසමේ බුල්නෑව ප්‍රදේශයේ නිවසක් රුපියල් පන්කෝටි හැත්තැදෙලක්ෂ හැටඅටදහාක් 268 000 වටිනා ප්‍රාඩෝ වර්ගයේ රථයක් භාණ්ඩ මුදල් ජංගම දුරකථන කොල්ලකෑමක් සම්බන්ධයෙන් ගල්නෑව පොලිස් ස්ථානයට පැමිණිල්ලක් විමර්ශන ආරම්භ තිබුණි 2025 ගල්නෑව පොලිස් ස්ථානයේ නිලධාරීන් විසින් ඉහත අපරාධයට සම්බන්ධ සැකකරුවන් හයදෙනෙකු කුරුණෑගල මාතවතගම විල්ගමුව ප්‍රදේශවලදී හෙරොයින් ග්‍රෑම් මිලිග්‍රෑම් 300 අයිස් මත්ද්‍රව්‍ය ග්‍රෑම් මිලිග්‍රෑම් 250 අපරාධයට යොදාගත් අත්වැසුම් අපරාධයට යතුරුපැදියක් රථයක් රථයක් සමඟ අත්අඩංගුවට සැකකරුවන් අවුරුදු වයස්වල පසුවන කුරුණෑගල නුගගොල්ල මාවතගම මැල්සිරිපුර මහනුවර ප්‍රදේශවල පදිංචිකරුවන් සැකකරුවන් විසින් කොල්ලකන ප්‍රාඩෝ වර්ගයේ රථය මීගලෑව ප්‍රදේශයේ තිබියදී සොයාගෙන තවද කොල්ලකන මුදලින් රුපියල් පනස්නමලක්ෂ තිස්නමදාහක 939 000 මුදලක් කොල්ලකන මුදල් වලින් උපයාගන්නා දේපළ රැසක් විමර්ශන නිලධාරීන් භාරයට සැකකරුවන් 2025 කැකිරාව මහේස්ත්‍රාත් අධිකරණයට ඉදිරිපත් වැඩිදුර විමර්ශන සඳහා 2025 දක්වා රැඳවුම් නියෝග ලබාගෙන ගල්නෑව පොලිසිය වැඩිදුර විමර්ශන කරනු ලබයි

In [27]:
# Build documents for semantic embedding and topic representation
def build_document(title, body):
    title = str(title).strip()
    body = str(body).strip()
    return f"{title}. {body}" if title else body


df["document"] = df.apply(lambda row: build_document(row["title"], row["text"]), axis=1)
documents = df["document"].tolist()

print(f"Documents: {len(documents)}")
documents[0][:500]
print(df["text"][10])

Documents: 1999
2025 රාත්‍රී කාලයේ ගල්නෑව පොලිස් වසමේ බුල්නෑව ප්‍රදේශයේ නිවසක් රුපියල් පන්කෝටි හැත්තැදෙලක්ෂ හැටඅටදහාක් 268 000 වටිනා ප්‍රාඩෝ වර්ගයේ රථයක් භාණ්ඩ මුදල් ජංගම දුරකථන කොල්ලකෑමක් සම්බන්ධයෙන් ගල්නෑව පොලිස් ස්ථානයට පැමිණිල්ලක් විමර්ශන ආරම්භ තිබුණි 2025 ගල්නෑව පොලිස් ස්ථානයේ නිලධාරීන් විසින් ඉහත අපරාධයට සම්බන්ධ සැකකරුවන් හයදෙනෙකු කුරුණෑගල මාතවතගම විල්ගමුව ප්‍රදේශවලදී හෙරොයින් ග්‍රෑම් මිලිග්‍රෑම් 300 අයිස් මත්ද්‍රව්‍ය ග්‍රෑම් මිලිග්‍රෑම් 250 අපරාධයට යොදාගත් අත්වැසුම් අපරාධයට යතුරුපැදියක් රථයක් රථයක් සමඟ අත්අඩංගුවට සැකකරුවන් අවුරුදු වයස්වල පසුවන කුරුණෑගල නුගගොල්ල මාවතගම මැල්සිරිපුර මහනුවර ප්‍රදේශවල පදිංචිකරුවන් සැකකරුවන් විසින් කොල්ලකන ප්‍රාඩෝ වර්ගයේ රථය මීගලෑව ප්‍රදේශයේ තිබියදී සොයාගෙන තවද කොල්ලකන මුදලින් රුපියල් පනස්නමලක්ෂ තිස්නමදාහක 939 000 මුදලක් කොල්ලකන මුදල් වලින් උපයාගන්නා දේපළ රැසක් විමර්ශන නිලධාරීන් භාරයට සැකකරුවන් 2025 කැකිරාව මහේස්ත්‍රාත් අධිකරණයට ඉදිරිපත් වැඩිදුර විමර්ශන සඳහා 2025 දක්වා රැඳවුම් නියෝග ලබාගෙන ගල්නෑව පොලිසිය වැඩිදුර විමර්ශන කරනු ලබයි

In [24]:
print("Sample document:", documents[10:50])

Sample document: ['බුල්නෑව නිවසක් බිඳ ජීප් රථයක්, රන් භාණ්ඩ හා මුදල් කෝල්ල කෑ සැකකරුවන් අල්ලයි. 2025 රාත්\u200dරී කාලයේ ගල්නෑව පොලිස් වසමේ බුල්නෑව ප්\u200dරදේශයේ නිවසක් රුපියල් පන්කෝටි හැත්තැදෙලක්ෂ හැටඅටදහාක් 268 000 වටිනා ප්\u200dරාඩෝ වර්ගයේ රථයක් භාණ්ඩ මුදල් ජංගම දුරකථන කොල්ලකෑමක් සම්බන්ධයෙන් ගල්නෑව පොලිස් ස්ථානයට පැමිණිල්ලක් විමර්ශන ආරම්භ තිබුණි 2025 ගල්නෑව පොලිස් ස්ථානයේ නිලධාරීන් විසින් ඉහත අපරාධයට සම්බන්ධ සැකකරුවන් හයදෙනෙකු කුරුණෑගල මාතවතගම විල්ගමුව ප්\u200dරදේශවලදී හෙරොයින් ග්\u200dරෑම් මිලිග්\u200dරෑම් 300 අයිස් මත්ද්\u200dරව්\u200dය ග්\u200dරෑම් මිලිග්\u200dරෑම් 250 අපරාධයට යොදාගත් අත්වැසුම් අපරාධයට යතුරුපැදියක් රථයක් රථයක් සමඟ අත්අඩංගුවට සැකකරුවන් අවුරුදු වයස්වල පසුවන කුරුණෑගල නුගගොල්ල මාවතගම මැල්සිරිපුර මහනුවර ප්\u200dරදේශවල පදිංචිකරුවන් සැකකරුවන් විසින් කොල්ලකන ප්\u200dරාඩෝ වර්ගයේ රථය මීගලෑව ප්\u200dරදේශයේ තිබියදී සොයාගෙන තවද කොල්ලකන මුදලින් රුපියල් පනස්නමලක්ෂ තිස්නමදාහක 939 000 මුදලක් කොල්ලකන මුදල් වලින් උපයාගන්නා දේපළ රැසක් විමර්ශන නිලධාරීන් භාරයට සැකකරුවන් 2025 කැකිරාව මහේස්ත්\u200dරාත් අධිකරණයට ඉදිරිපත් වැඩිදුර විමර්ශන සඳහා 2025 දක්වා රැඳවුම් නියෝග ලබාගෙන ගල්නෑව පොලිසිය වැඩිදුර විමර්ශන කරනු ලබයි', 'දින 8කින් ලංකාව පුරා තනිව සංචාරය කළ චිත්\u200dර ශිල්පිනිය සමන්මලී ලැබූ අත්දැකීම්. වසරක අවසානය සිහිනයක් ගැනීමට කාන්තාවක සිටියේ නොඉවසිල්ලෙනි මෝටර් සයිකලයෙන් ලංකාව යාමට අවුරුද්දක් සැලසුම් ගමන ආරම්භ කිරීමට වේයන්ගොඩ ප්\u200dරදේශයේ ජීවත් හැවිරිදි වෘත්තීයෙන් චිත්\u200dර ශිල්පිනියකි මෝටර් සයිකලයෙන් තනිව සංචාර කිහිපයක් සමන්මලී තුෂාරා තමන් සේවය කරන ආයතනයෙන් ගමනට අවශ්\u200dය නිවාඩු අනුමත ගැනීමෙන් සංචාරය ආරම්භ කිරීම සඳහා වසරක කාලයක් බීබීසී සිංහල සමග අදහස් දක්වමින් පැවසුවා වසරක් හොඳින් සැලසුම් අටකින් කිලෝමීටර් 822කින් ලංකාව ඇයගේ අත්දැකීම බීබීසී සිංහල පැහැදිලි අයුරිනි මුලින් බයික් ගමනක් මාතර තාත්තාගේ අම්මාව බලලා එන්න යද්දී ගොඩක් ලස්සන එහෙම කරගෙන ගමනත් එක්ක බයික් එකෙන් සංචාරය කරන්න අදහස සමන්මලී තුෂාරා පවසයි සොබාදහමේ ඡායාරූප ගැනීමට උනන්දු අතර මෝටර් සයිකලයෙන් එවැනි යාමට පටන්ගෙන පායන බහින බලන්න ආසයි එතකොට ඒවගේ ලස්සන දේවල් ගන්නත් ආසයි ඒකත් එක්ක තනියම විදිහේ ගමන් යන්න පටන් ගත්තා පැවසුවා ජයමාන්න ලංකාවේ උසම ඇල්ල නෙලුම් කුලුණෙන් පහළට බැස්ස ලංකාවේ පළමු කාන්තාව අනුව අම්පාර ආරුගම්බේ පොළොන්නරුව යාපනය ප්\u200dරදේශවල සංචාරය නමුත් දිගට ලංකාව ගමන් ගන්නා චාරිකාවක් සඳහා සූදානම සැලසුම්සහගතව සඳහා ගමනට කලින් බයික් සම්පූර්ණ පරීක්ෂාවක් කරලා අඩුපාඩු පවසයි ඇයට අවශ්\u200dය ඇඳුම් පහසුවෙන් සොයාගත ආකාරයට අසුරාගෙන අත්\u200dයවශ්\u200dය ඖෂධ අත්\u200dයවශ්\u200dය ලියකියවිලි කබායක් අත්\u200dයවශ්\u200dය භාණ්ඩ පමණක් ගමනට කරගෙන දෙසැම්බර් ආරම්භ චාරිකාව අවසන් ඇත්තේ ජනවාරි වනදා ගමන පැයට කිලෝමීටර් අතර වේගයක් පවත්වා පැවසුවා රාත්\u200dරී වෙන්න කලින් නවාතැනට කෑමත් අරගෙන නවාතැන් ගනිද්දී ගූගල් රිවීව් එහෙම බලලා තමයි ගත්තේ අදාළ දවසේ තමයි නවතින හොයාගෙන විස්තර සාමාන්\u200dය සැහැල්ලු ඇඳුම් ඇඳලා පහසුවක් අවධානයක් ලැබුණේත් පවසයි නවාතැනට ගියාට පස්සේ විවේකයක් ගත්තා විවේකයක් ගත්තා මහන්සි දැනෙන අඩුයි සමන්මලී පවසයි පළමු දිනය වේයන්ගොඩ කල්පිටියදෙවන දිනය කල්පිටිය මන්නාරමතුන්වන දිනය මන්නාරම යාපනයහතරවන දිනය යාපනය මුලතිව්පස්වන දිනය මුලතිව් ත්\u200dරිකුණාමලයහයවන දිනය ත්\u200dරිකුණාමලය ආරුගම්බේහත්වන දිනය ආරුගම්බේ වැලිගමඅටවන දිනය වැලිගම වේයන්ගොඩ සමන්මලීට අතරමගදී හමුවූ සමග කිරීමේදී දෙනෙකු තනිව සංචාරය පිළිබඳව පුදුමයට පත්වූ පැවසුවා නැවතුණු තැන්වල එහෙම ගොඩක් පුදුම එහෙම යනවා කිව්වා හැබැයි ගොඩක් සතුටු සහයෝගයක් දුන්නා සිහිපත් කරයි විදේශීය කාන්තාවකුත් නෙවෙයි ලංකාවේ කෙනෙක් එයාලා තවත් පුදුම විස්තර එහෙම අහනවා ගමන යාපනය ප්\u200dරදේශයේ සංචාරය දිනයේදී ඇයට තවත් අපූරු අත්දැකීමක් තිබිණි යාපනයට ගිහින් නවතින තැනින් තියලා කයිට්ස් පැත්තට එතන ජැටියකින් වෙලාවේ පාලම් පාරුවක් වෙන්න හදමින් හිටියේ ගිහින් ඇහුවා මමත් එන්න කියලා කීයක් ගන්නවා කියලා සල්ලි එන්න කියලා කිව්වා බයික් එකත් අරගෙන ඒකට නැග්ගා පැවසුවා පාරුවේ හිටියා කෙනෙක් එයාට කරන්න භාෂාවෙන් මගෙන් ඇහුවේ අරන් කැමරාව මමත් පුළුවන් විදිහට කිව්වා කැමරාවක් කියලා ගමනේදී ලංකාවේ විශාලතම වනෝද්\u200dයාන දෙකක් විල්පත්තු වනෝද්\u200dයාන සීමාවන් වනෝද්\u200dයාන හරහා යාමට නොහැකි අභ්\u200dයන්තරයෙන් ගමන් බලාපොරොත්තුවෙන් හිටියා අලියෙක් හම්බ කියලා නමුත් අලියෙක් ගමනේදී හම්බ මුලතිව් හරියේදී එහෙමත් තිබුණු හිතුවෙන් අලියෙක් ගැහෙයි කියලා නමුත් ඇයට මුලතිව් ප්\u200dරදේශයේදී වෙනත් අමුත්තෙකු හමුවූ පැවසුවා මුලතිව් ඉඳලා නයාරු පැත්තට කියන්නේ කෝකිලායි කලපුව පැත්තට යනකොට එහෙම පාරවල් පාළුයි පාරෙන් යන්න පහුගිය දවස්වල පාලම කැඩිලා තිබුණ එතනින් ආපස්සට එනකොට ටැමිල් අම්මා කෙනෙක් හම්බ පැවසුවා අඩුයි අම්මා හෙල්මට් එකකුත් දාගෙන පාරට බලාගෙන ඉන්නවා බයික් එකක් නවත්වලා යන්න එද්දිත් විදිහට නැවැත්තුවා නවත්වලා දෙමළෙන් කිව්වා මුලතිව්වලට යන්න ඉන්නේ කියලා පස්සේ එයාව මුලතිව්වලින් දාගෙන පැවසුවා සංචාරය සඳහා ඇයට වියදම් මුදල් සම්බන්ධයෙන් තොරතුරු ගත්තා අනුව ඇයට අටක සංචාරය සඳහා ආසන්න වශයෙන් මුදල 000කි වසරක් සැලසුම් සංචාරය අවසන් නැවත වේයන්ගොඩ නිවසට පැමිණ ඇත්තේ 2026 ජනවාරි මාර්ග නොකොට කිසිදු ආකාරයක අපහසුතාවකට නැවත පැමිණීමට සම්බන්ධයෙන් සතුටු පැවසුවා කල්පිටියේදී පොලිසියෙන් පස්සේ තැන්වලින් පැවසුවා එහිදී බීබීසී සිංහල මීළඟට සංචාරය පිළිබඳව සමන්මලීගෙන් විමසී කලින් මන්දාරම් නුවර වෙලාවේදී පවුලක් පැවසුවා එයාලා එක්ක ගොඩක් හිතවත් පහුගිය දවස්වලදී තත්ත්වයත් එක්ක එයාලට කරදර බලාපොරොත්තු වෙනවා එයාලව බලලා එන්න මන්දාරම් නුවර ගිහින් එන්න සමන්මලී පැවසුවා', 'ශ්\u200dරී ලංකා - කොදෙව් පළමු T20 තරගය අද. ලංකාව බටහිර ඉන්දීය කොදෙව් කණ්ඩායම සමඟ පැවැත්වෙන තරග 3කින් සමන්විත 20යි තරගාවලියේ පළමු තරගය රංගිරි දඹුල්ල ක්\u200dරිකට් ක්\u200dරීඩාංගණයේදී පැවැත්වෙයි දෙරට අතර වනවිට 20යි තරග 15ක් පවත්වා අතර තරග ලංකාව හිමිකර ගනිද්දී කොදෙව් කණ්ඩායම තරග හිමිකරගෙන වෙතත් කණ්ඩායමක් කොදෙව්වන්ට එරෙහිව 20යි තරගාවලි ජයක් මෙතෙක් හිමිකරගෙන නොමැත අතර තරගයට ක්\u200dරීඩාකරන කණ්ඩායමේ අවසන් 11දෙනා ප්\u200dරකාශ කරනු ලැබීය කණ්ඩායම වන්නේ නායක චරිත් අසලංක පැතුම් නිස්සංක කුසල් මෙන්ඩිස් කුසල් ජනිත් පෙරේරා කමිඳු මෙන්ඩිස් භානුක රාජපක්ෂ වනිඳු හසරංග මහිෂ් තීක්ෂණ චමිඳු වික්\u200dරමසිංහ මතීෂ පතිරණ අසිත ප්\u200dරනාන්දුයි අවස්ථාවේදී අදහස් දැක්වූ ක්\u200dරිකට් කණ්ඩායමේ නායක චරිත් අසලංක දැක්කා දසුන් ශානක කණ්ඩායමෙන් ඉවතට පිතිකරුවෙක් වශයෙන් තමයි මමත් පුහුණුකරු තේරුම් කමිටුවත් කතාවෙලා නැවත භානුකව කණ්ඩායමට ගෙනාවේ භානුක රාජපක්ෂගෙන් කණ්ඩායම වැඩිපුරම බලාපොරොත්තු වෙන්නේ එයාගේ අත්දැකීම් වෙලාවේ භානුක රාජපක්ෂ කියන්නේ 20යි තරග ගොඩක් ක්\u200dරීඩා කරලා තියෙන අත්දැකීම් බහුල ක්\u200dරීඩකයෙක් කණ්ඩායමට වැදගත් එයාගේ අත්දැකීම ඉතින් අත්දැකීම අපට වැදගත් අත්දැකීමත් සමග කියන්නේ පවර්හිටින් පැත්ත තමයි භානුක විශේෂයෙන් කණ්ඩායමට කැඳෙව්වේ මොකද එයාට වෙලාවක හයක් ගහන්න පුළුවන් වේලාවට වෙනස් කරලා රොටෙට් කරන් සෙල්ලම් කරන්න පුළුවන් තමයි ප්\u200dරධාන හේතුව භානුක රාජපක්ෂ කැඳවීමට', 'පල්ලි පන්සල් පිළිසකර කිරීමට ප්\u200dරමුඛතාව දෙන්න. ගංවතුරෙන් නායයාමෙන් විපතට ජනතාවට උපරිම සහන සලසන ගමන් විනාශයට විහාරස්ථාන පල්ලි කෝවිල් ඇතුළු සියලු පූජ්\u200dයස්ථාන පිළිසකර කිරීමට ප්\u200dරමුඛතාව ලබාදෙන පෙරමුණේ ජාතික සංවිධායක මන්ත්\u200dරී නාමල් රාජපක්ෂ රජයෙන් ඉල්ලා තමන්ට තොරතුරු අනුව මධ්\u200dයම වයඹ සබරගමුව බස්නාහිර දකුණ උතුරු නැගෙනහිර ප්\u200dරදේශවල විහාරස්ථාන කතෝලික පල්ලි හින්දු කෝවිල් මුස්ලිම් පල්ලි ඇතුළු ආගමික ස්ථාන ගණනකට ගංවතුරින් සිදුවී තිබෙන බවද මන්ත්\u200dරීවරයා පැවසීය පිළිබඳව රජයේ විධිමත් සමීක්ෂණයක් සිදුකර කඩිනම් පියවර', 'විස්කි ඉස්සූ සිද්ධියේ සැකකරු රිමාන්ඩ්. කොළඹ මහෙස්ත්\u200dරාත් අධිකරණයේ භාණ්ඩ රුපියල් විස්කි බෝතල් අතුරුදන්වූ සිද්ධිය සම්බන්ධයෙන් අත්අඩංගුවට සැකකරු එළඹෙන වනදා රක්ෂිත බන්ධනාගාරගත සිද්ධිය සම්බන්ධයෙන් පසුගියදා අධිකරණ අමාත්\u200dය විජයදාස රාජපක්ෂ මහතා පාර්ලිමේන්තුවේදී අනාවරණයක් කළේය එහිදී වැඩිදුරටත් සඳහන් නියමිත යතුරෙන් කාමරයේ විවෘත සොරකම සිදුකර බවට පරීක්ෂක වාර්තාවෙන් අනාවරණය බවය', 'ඊශ්\u200dරායල ජාතිකයින් විසින් සිදුකරන ඉදිකිරීම්වලට අවසර දීලා නැහැ - අගමැති. ඊශ්\u200dරායල ජාතික ආගමික මධ්\u200dයස්ථාන සමාන ස්ථාන ගොඩනැගීම සඳහා රජයේ කිසිදු ආයතනයකින් අවසරයක් ලබාදී නොමැති අග්\u200dරාමාත්\u200dය ආචාර්ය හරිනි අමරසූරිය පවසයි පාර්ලිමේන්තු මන්ත්\u200dරී මුජිබුර් රහුමාන් මහතා පාර්ලිමේන්තුවේදී යොමුකළ ප්\u200dරශ්නයක පිළිතුරු දෙමින් සඳහන් කළාය ඊශ්\u200dරායල ජාතිකයින් ආගමික මධ්\u200dයස්ථාන සමාන ස්ථාන ගොඩනැගීම සඳහා දක්වා බුද්ධශාසන ආගමික සංස්කෘතික කටයුතු අමාත්\u200dයාංශය යටතේ පවතින දෙපාර්තමේන්තු මගින් අවසර ලබාදීමක් සිදුකර නමුත් දන්නවා ඔවුන් එවැනි මධ්\u200dයස්ථාන පවත්වාගෙන බවට සම්බන්ධයෙන් අපිට තොතරු ලැබිලා තියෙනවා පිළිබඳව නිරීක්ෂණයක් කරලා තියෙනවා අවසරයෙන් කරන නෙමෙයි කිසිවිටක අවසරයක් පිළිබඳව මොකද්ද සිදුකළ යුතුතේ කියන පිළිබඳව සාකච්ඡා කරනවා නවත්නවන් කුමක්ද යුත්තේ විදෙස් කටයුතු අමාත්\u200dයාංශය මගින් මැදිහත්වීමක් සිදුවෙනවා එහිදී පාර්ලිමේන්තු මන්ත්\u200dරී මුජිබුර් රහුමාන් මහතා පෙන්වා දුනේන වනවිට ලංකාවේ විවිධ ප්\u200dරදේශවල ඊශ්\u200dරායල් ආගමික මධ්\u200dයස්ථාන සංස්කෘතික මධ්\u200dයස්ථාවටල ආරක්ෂක අමාත්\u200dයංශය මගින් අවරසය ලබාදී ගොඩනගමින් පවතින බවය එවැනි ස්ථානවලට පොලිස් විශේෂ කාර්ය බළකායේ ආරක්ෂාව යොදවා පාර්ලිමේන්තු මන්ත්\u200dරී මුජිබුර් රහුමාන් මහතා වැඩිදුරටත් පැවසීය', 'සාපෙළ සමීක්ෂණ ගාස්තු ගැන අමාත්\u200dයාංශයෙන් නිවේදනයක්. සාමාන්\u200dය පිළිතුරු පත්\u200dර සමීක්ෂණය සඳහා ගුරුවරුන්ට පරීක්ෂකවරුන්ට ගෙවනු ලබන දීමනාව කිරීමට අදාළ අමාත්\u200dය මණ්ඩල සංදේශය ඉදිරිපත් තිබෙන අධ්\u200dයාපන අමාත්\u200dයාංශය නිවේදනයක් නිකුත් කරමින් පවසයි සඳහා කමිටු වාර්තා 2024 ලැබීමට නියමිත අතර වාර්තාව මීළඟ අමාත්\u200dය මණ්ඩලයට ඉදිරිපත් කිරීමටත් අනුව දීමනා කිරීමටත් අපේක්ෂිත නි\u200cවේදනයේ වැඩිදුරටත් දැක්\u200cවෙයි', 'පාර්ලිමේන්තුව අද යළි රැස්වෙයි. ලබන දක්වා පාර්ලිමේන්තුව රැස්වීමට නියමිත පාර්ලිමේන්තු මහලේකම් කාර්යාලය සඳහන් කළේය සේවකයන්ගේ අයවැය සහන දීමනා සංශෝධන පනත් කෙටුම්පත සේවකයන්ගේ ජාතික අවම වේතනය සංශෝධන පනත් කෙටුම්පත ඇතුළු පනත් කෙටුම්පත් දිනයේ විවාදයට ගැනීමට නියමිතව දිනයේ සමාගම් සංශෝධන පනත් කෙටුම්පත දෙවන කියවීමේ විවාදය පැවැත්වීමට නියමිත අතර අනිද්දා දිනයේ විදුලි සංශෝධන පනත් කෙටුම්පත දෙවන කියවීමේ විවාදය පැවැත්වීමට නියමිතය අතර ඉදිරි පාර්ලිමේන්තු සතිය සම්බන්ධයෙන් සාකච්ඡා කිරීම සඳහා විපක්ෂයේ පාර්ලිමේන්තු කණ්ඩායම් රැස්වීම පස්වරුවේ රැස්වුණි අතර දිනයේ ආණ්ඩුක්\u200dරම ව්\u200dයවස්ථා සභාව රැස්වීමට නියමිතව කථානායක ජගත් වික්\u200dරමරත්න මහතාගේ ප්\u200dරධානත්වයෙන් ආණ්ඩුක්\u200dරම ව්\u200dයවස්ථා සභාව රැස්වීමට නියමිත වාර්තා මෙහිදී අගවිනිසුරුවරයෙකු පත්කිරීම සම්බන්ධයෙන් ජනාධිපතිවරයාගේ යෝජනා පිළිබඳව අවධානය යොමුකිරීමට නියමිත සඳහන් අගවිනිසුරු මුර්දු ප්\u200dරනාන්දු මහත්මිය ලබන විශ්\u200dරාම යෑමට නියමිත අතර පුරප්පාඩුව සඳහා අගවිනිසුරුවරයෙකු පත්කිරීමට නියමිතය', "මට කියන්නේ ජංගම සුපර්මාර්කට් එක කියලා.'. කිසිවක් අඩංගු වීඩියෝ ශීර්ෂ වැකිය ඉදිකට්ට පිස්ස සෙරප්පු ඉඳලා දෙයක්ම තියෙනවා මහනුවර පිළිමතලාවේ පදිංචි වින්සන් ජගත් ගණනක් භාණ්ඩ ශරීරයේ එල්ලාගෙන ජංගම වෙළඳාමේ නිරත පුද්ගලයකි භාණ්ඩ වර්ග 300ක් පමණ අතර අලෙවි කිරීමට දිනකට කිලෝමීටර් පමණ ගමන් කරන පවසයි ඉදිකට්ට පිස්සා සෙරප්පු ඉඳලා දෙයක්ම තියෙනවා දරුවන්ට රටට ණයකාරයෙක් වෙන්න කැමති කාටවත් අතපාන්නෙත් එකම බලාපොරොත්තුව මටත් හොඳට දරුවෝ ඉන්නවා දකින්න යනුවෙන් BBC සිංහල පැවසුවේය", 'ලෝක කුසලානය අතරේ ක්\u200dරිකට් තරු දෙකක් විවාහ ගිවිස ගනිති. ලංකාවේදී දිනවල පැවැත්වෙන 2025 ගෘහස්ත ක්\u200dරිකට් තරගාවලියට සහභාගී සඳහා පැමිණ සිටින අතරතුරේදී එංගලන්ත ගෘහස්ථ පිරිමි ක්\u200dරිකට් කණ්ඩායමේ නායක පටෙල් එරට ගෘහස්ත කාන්තා ක්\u200dරිකට් කණ්ඩායම් සාමාජිකා මැලෝරි බාර්ටොෂ් විවාහ ගිවිස ගත්හ පවුල්වල සාමාජික සාමාජිකාවන් පිරිසක් ඉදිරියේ යුවළ ගල්කිස්ස හෝටලයේදී මංගල කරගත් අවස්ථාව 2025 ගෘහස්ත ක්\u200dරිකට් තරඟාවලිය තලවතුගොඩ ඕස්ට්\u200dරේෂියා ගෘහස්ත ක්\u200dරිකට් ක්\u200dරීඩාංගනයේදී දිනවල පැවැත්වේ', 'අවුරුදු තුනකින් නාගරික ගෙවල් පන්දාහක්. ඉදිරි වසර ඇතුළත නාගරික ජනතාවට ගෙවල් පන්දාහක් හදන්න බලාපොරොත්තු නාගරික සංවර්ධන ඉදිකිරීම් නිවාස අමාත්\u200dය අනුර කරුණාතිලක මහතා පාර්ලිමේන්තුවේදී පැවසීය ප්\u200dරතිපත්ති ප්\u200dරකාශනය ඉදිරිපත් කරන විටම පළමු පියවර යටතේ මෙපමණ ප්\u200dරමාණයක් තේරුම් තිබෙනවා ජාත්\u200dයන්තර මූල්\u200dය අරමුදල සම්බන්ධයෙන් ප්\u200dරතිපත්ති ප්\u200dරකාශයේ පැහැදිලි සඳහනක් තිබෙනවා දුප්පත් ජනතාව තත්ත්වයෙන් ගැනීම සඳහා මූල්\u200dය අරමුදල සමග නැවත සාකච්ඡා කරන සඳහන් සහන ලබාදිය ඉලක්ක සහගත කණ්ඩායම් සඳහා වැඩසටහන් සැකසීමට කටයුතු අස්වැසුම ප්\u200dරතිලාභ කිරීමට කටයුතු සිසුන් සඳහා ප්\u200dරවේශ දීමනා සුභසාධන වියදම කිරීමට කටයුතු පැත්තකින් මූල්\u200dය විනය පවත්වා ගැනීම සඳහා කටයුතු තිබෙනවා වගේම මූල්\u200dය විනය පවත්වා ගැනීමෙන් ලැබුණු ප්\u200dරතිලාභය ජනතාවට ලබාදීමට කටයුතු තිබෙනවා වසරේ රැකියා නියුක්තිය සීයට දෙකකින් වසර ඇතුළත නාගරික ජනතාවට ගෙවල් පන්දාහක් හදන්න බලාපොරොත්තු වෙනවා අපිට ඉස්සරහට යන්න තියෙන්නේ ආර්ථික අර්බුදයේ කරගහගෙන යනුවෙන්ද අමාත්\u200dයවරයා', 'විෂ මත් මඩිද්දී කඹ ඇදිලි එපා. දේශපාලන ආර්ථික කරුණු සම්බන්ධයෙන් විවාද නමුත් මත්ද්\u200dරව්\u200dය උවදුර රටින් තුරන් දැමීමේ ජාතික වගකීම කිරීමේදී තවදුරටත් කිසිදු විවාදයකට ඉඩක් නොමැති ජනාධිපති අනුර කුමාර දිසානායක මහතා පැවැසීය මත්ද්\u200dරව්\u200dය උවදුර මුලිනුපුටා දැමීමේ කඩිනම් වැඩපිළිවෙළක් වෙනුවෙන් රටම එකට බවද ජනාධිපතිවරයා අවධාරණය කළේය ජනාධිපතිවරයා සඳහන් මත්ද්\u200dරව්\u200dය මුලිනුපුටා දැමීම සඳහා රටම එකට ජාතික මෙහෙයුම පිළිබඳ මාධ්\u200dය ආයතන ප්\u200dරධානීන් දැනුවත් කිරීම වෙනුවෙන් ජනාධිපති කාර්යාලයේ පැවති හමුවට වෙමිනි මත්ද්\u200dරව්\u200dය ජාවාරම බැදුණු අපරාධ කල්ලිවල මූල්\u200dය බලය විසින් ආර්ථිකය සමාජ දේහය රාජ්\u200dය යාන්ත්\u200dරණය නීතියේ විධානයේ ආධිපත්\u200dය වට්ටමින් රටත් සමාජයත් විනාශ කරමින් තිබෙන ජනාධිපතිවරයා සඳහන් කළේය උවදුරට තවදුරටත් නොතැබීමට වත්මන් රජය තීරණය තිබෙන පැවසු ජනාධිපතිවරයා වෙනුවෙන් සියලු දෙනාගේ දායකත්වය අපේක්ෂා කරන බවද පැවසීය එමෙන්ම පසුගිය සමයේ දේශපාලන රශ්මි කදම්භය නිදැල්ලේ වර්ධනය අපරාධ රටත් සමාජයත් දැඩිව වෙළාගෙන තිබෙන අන්දම පොලිසිය රේගුව මෝටර් ප්\u200dරවාහන දෙපාරත්මේන්තුව ආගමන විගමන දෙපාර්තමේන්තුව ඇතුළු රජයේ වගකිවයුතු ආයතනවලින් සහාය පිළිබඳවද ජනාධිපතිවරයා මෙහිදී සිහිපත් කළේය නැවත එවැනි තත්ත්වයකට නොතබා අනාගත පරපුර වෙනුවෙන් ජාතික ව්\u200dයසනය පරාජය කිරීමට සියලු පැවරි අත්හළ නොහැකි වගකීම ජනාධිපතිවරයා මෙහිදී වැඩිදුරටත් අවධාරණය කළේය රටම එකට ජාතික මෙහෙයුම සමාරම්භය ජනාධිපති අනුර කුමාර දිසානායක මහතාගේ ප්\u200dරධානත්වයෙන් කොළඹ සුගතදාස ගෘහස්ථ ක්\u200dරීඩාංගණයේදී වැනිදා පෙරවරු 10ට පැවැත්වේ සෞඛ්\u200dය ජනමාධ්\u200dය අමාත්\u200dය වෛද්\u200dය නලින්ද ජයතිස්ස ජනාධිපති ලේකම් ආචාර්ය නන්දික සනත් කුමානායක මහත්වරු රාජ්\u200dය පෞද්ගලික විද්\u200dයුත් මුද්\u200dරිත මාධ්\u200dය ආයතන ප්\u200dරධානීහු නියෝජිතයෝ විනෝදාස්වාද කර්මාන්තයට අදාළ ආයතන ප්\u200dරධානීහු ඇතුළු පිරිසක් අවස්ථාවට එක්ව සිටියහ', "අතුරුදන්වූවන්ගේ ඥාතීන්ගේ විරෝධතාවට වසර 7: 'ජාත්\u200dයන්තර විමර්ශනයක් අවශ්\u200dයයයි'. කිසිවක් අඩංගු Play video අයිතීන් ගන්න අරගල කිරීම මාවතක් තියෙනවා කියලා හිතන්නේ ධාවන කාලය 5602 56වීඩියෝ ශීර්ෂ වැකිය අයිතීන් ගන්න අරගල කිරීම මාවතක් තියෙනවා කියලා හිතන්නේ යුද්ධයෙන් අතුරුදන්වූවන්ගේ උතුරු නැගෙනහිර පළාත් ඥාතීන් පවත්වන අඛණ්ඩ විරෝධතා උපවාස මාලාවට වසර හතක් ගතවීම නිමිත්තෙන් අතුරුදන්වූවන් සොයාදෙන ලෙසට ඉල්ලා අතුරුදන්වූවන්ගේ ඥාතීහූ පෙබරවාරි වැනිදා කිලිනොච්චිය නගරයේදී විරෝධතා පාගමනක් පැවැත්වූහ ඔවුන් කිලිනොච්චිය කන්දසාමි කෝවිල අසළින් පාගමන ආරම්භ කරමින් කිලිනොච්චිය නගරය ඔස්සේ ගමන් කරමින් විරෝධතාව පවත්වනු ලැබීය කිලිනොච්චිය යාපනය වවුනියාව මුලතිව් මන්නාරම දිස්ත්\u200dරික්කවල අතුරුදන්වූවන්ගේ ඥාතීන්ගේ සංගම් විසින් විරෝධතාවය පැවැත්වනු ලැබූහ යුද්ධයෙන් අතුරුදන්වූවන් සොයාදෙන ලෙසට ඉල්ලීම් කරමින් 2017 පෙබරවාරි වැනිදා අතුරුදන්වූවන්ගේ ඥාතීන් විසින් විරෝධතාවය ආරම්භ කරනු ලැබීය විරෝධතාවයට එක්වු කිලිනොච්චිය දිස්ත්\u200dරික් අතුරුදන්වූවන්ගේ සංගමයේ සභාපති කනගරංජනි පැවසුවාය යුද්දේ කාලයේ අතුරුදන්වු ඥාතීන් සොයාදෙන ලෙසට ආරම්භ විරෝධතාවයට අදට අවුරුදු හතක් ගතවෙනවා අපිට කිසිදු සාධාරණයක් වෙනකම් ඉටුවෙලා යුද්ධය ඉවරවෙලා අවුරුදු පහළොවකට කාලයක් ගතවෙලා දක්වා පත්වුණු කිසිදු රජයක් සමයේ අතුරුදන්වූවන් සොයාදීමට කටයුතු කරලා කිසිම ආණ්ඩුවක් කිසිම පාලකයෙක් තමන්ගේ ඉල්ලීම් වෙනුවෙන් සාධාරණය ඉටුකරදීමට උත්සහ කරලාවත් ඉල්ලන්නේ ඥාතීන් කොහේද කියලා හොයලා දෙන්න කියලා විතරයි පැවසුවාය අවුරුදු හතක් කිලිනොච්චිය කන්දසාමි කෝවිල ඉදිරිපිට ඉඳගෙන ඥාතීන් හොයලා දෙන්න කියලා ඉල්ලීම් ගැටළුවට දක්වා කිසිම සහනයක් ලැබුණේ උතුරු නැගෙනහිර අතුරුදන්වූවන්ගේ ඥාතීන් විරෝධතාවකඋතුරු නැගෙනහිර අතුරුදහන්වූවන්ගේ ඥාතීන්ගේ අඛණ්ඩ උපවාසයට 2000 ඉල්ලන්නේ ජාත්\u200dයන්තරයේ රටවල් මැදිහත්වෙලා ගැටළුවට සාධාරණය ලබාදෙන්න කියලා දේශීය ක්\u200dරමවේදයකින් ගැටළුවට විසදුම් ලැබෙන්නේ කියලා දන්නවා ඊශ්\u200dරායල පලස්තීන ගැටළුව වෙලාවේ දකුණු අප්\u200dරිකාව රටවල් මැදිහත්වෙලා යුද්ධය වෙලාවේ අතුරුදන්වූවන් සම්බන්ධයෙන් ගැටළුවට සාධාරණ පිළිතුරක් ලබාදෙන්න ක්\u200dරමයක් හැදුවා අතුරුදන්වූවන් වෙනුවෙන් ජාත්\u200dයන්තර රටවල් මැදිහත්වෙලා සාධාරණයක් ලබාදෙන්න කියලා තමයි ඉල්ලන්නේ නායකයෝ හදන වැඩසටහන්වලින් අපිට යහපතක් ලැබෙයි කියලා විශ්වාස කරන්න කිලිනොච්චිය දිස්ත්\u200dරික් අතුරුදහන්වූවන්ගේ සංගමයේ ලේකම් ලීලාවති පැවසුවාය අතුරුදහන්වූවන් සොයාදෙන බවට පවසමින් රජය විසින් අතුරුදහන්වූවන් සොයාදීමේ කාර්යාලයක් ස්ථාපිත තවත් විවිධ ආයතන බිහිකරලා අතුරුදන්වූවන්ට සාධාරණය කරන්න කටයුතු කරනවා කිව්වා දක්වා අපිට යහපතක් දැනට යුද්දේ ඉවරවෙලා ආණ්ඩු තුනක් බිහිවුණත් කිසිදු රජයකින් අතුරුදහන්වූවන්ගේ ගැටළුවට විසදුම් ලබාදීලා අතුරුදහන්වූවන්ගේ අම්මලාගේ ඉල්ලීම පාලකයින් කවදාවත් අහන්නේ වෙනුවෙන් සාධාරණයක් ලබාදෙන්නෙත් පාලකයෝ පාරවල් දුක්විදින අම්මලා වෙනුවෙන් ඇහුම්කන් දෙන්නේ යනුවෙන් විරෝධතාවයට එක්වු සන්ධ්\u200dය එක්නැළිගොඩ පැවසුවාය වවුනියාව දිස්ත්\u200dරික් අතුරුදන්වූවන්ගේ සංගමයේ සභාපති රාජ්කුමාර් පැවසූවේ අතුරුදන්වූවන්ගේ ගැටළුව දෙමළ ජනතාවගේ ප්\u200dරශ්න විසදුම් ලබාදීමට රජයක්ම අපොහොසත් තියෙනවා අතුරුදහන්වූවන්ගේ ගැටළුවට විසදුම් ඉල්ලීම් කරමින් වර්තමාන ජනාධිපතිවරයා අගමැතිවරයා අවදියේ ඉල්ලීම් දක්වා වෙනුවෙන් සාධාරණය ඉටුවෙලා එක්සත් ජාතීන්ගේ සංවිධානය යුරෝපා සංගමය ඇමෙරිකාව ඇතුළු රටවල් මැදිහත් යුද්ධයෙන් අතුරුදහන්වු උතුරු නැගෙනහිර වැසියන් පිළිබඳ සාධාරණය ඉටුකරදිය යුතුයි යනුවෙන් පැවසීය අවස්ථා ගණනාවකදී රජය විසින් අතුරුදන්වූවන්ගේ ගැටළුව වෙනුවෙන් පිළිතුරු ලබාදෙන බවට ප්\u200dරකාශ කළද තමන්ගේ ගැටළුව වෙනුවෙන් මෙතෙක් පිළිතුරක් නොලැබීම කණගාටුවට කරුණක් බවද අතුරුදහන්වූවන්ගේ ඥාතීහූ පැවසූහ අතුරුදහන්වූවන්ගේ ඥාතීන් වැඩිදුරටත් සඳහන් උතුරු නැගෙනහිර නියෝජනය කරන දෙමළ දේශපාලන නායකයින්ද තමන්ගේ ගැටළුවට විසදුම් ලබාදීම වෙනුවෙන් මැදිහත්වීමක් නොකරන ජාත්\u200dයන්තරය මැදිහත්ව තමන්ගේ ගැටළුව වෙනුවෙන් විසදුම් ලබාදිය බවද විරෝධතාවයට එක්වු අතුරුදහන්වූවන්ගේ ඥාතීහූ ඉල්ලා සිටියහ යුද්ධය එළැඹෙන වසර වසර ගතවුවද අතුරුදන්වූවන් සම්බන්ධයෙන් සඳහනක් බැලීමක් නොමැතිවීමෙන් තමන් මහත් අසරණ සිටින විරෝධතාකරුවෝ පැවසූහ", 'ජනපති බුද්ධගයාව වැඳ පුදා ගනී. ඉන්දියාවේ සංචාරයක නිරත ජනාධිපති අනුර කුමාර දිසානායක දෙසැම්බර් වැනිදා පෙරවරුවේ බුද්ධගයාවට පැමිණ විහාරයත් බෝධීන් වහන්සේත් ආශීර්වාද ගත්තේය ඉන්දියානු මහාබෝධි සමාගමේ මහලේකම් පූජ්\u200dය පැලවත්තේ සීවලි ස්වාමීන්වහන්සේ සාරනාත් මධ්\u200dයස්ථානාධිපති පූජ්\u200dය රත්මල්වල සුමිත්තානන්ද ස්වාමීන්වහන්සේ විසින් ජනාධිපතිවරයාට ආශිර්වාද කරන ජනාධිපති මාධ්\u200dය අංශය සඳහන් කළේය විදේශ කටයුතු විදේශ රැකියා සංචාරක අමාත්\u200dය විජිත හේරත් කම්කරු අමාත්\u200dය ආර්ථික සංවර්ධන නියෝජ්\u200dය අමාත්\u200dය මහාචාර්ය අනිල් ජයන්ත ප්\u200dරනාන්දු අවස්ථාවට එක්ව සිටියහ ඉන්දියාවේ තෙදින සංචාරයක නිරත ජනාධිපති අනුර කුමාර දිසානායක නවදිල්ලි නුවර දෙසැම්බර් වැනිදා පස්වරුවේ ඉන්දීය පරිමාණ ව්\u200dයාපාරික නියෝජිතයන් සමඟ සාකච්ඡාවකට ඉන්දියානු කර්මාන්ත සම්මේලනය විසින් සංවිධානය කරන සාකච්ඡාවට ඉන්දියාවේ ප්\u200dරමුඛතම ව්\u200dයවසායකයන් සහභාගී ලංකාවේ ආයෝජනවලට හිතකර පරිසරය පහදා ජනාධිපති අනුර කුමාර දිසානායක ලංකාවේ ආයෝජනය කරන ඉන්දීය ව්\u200dයවසායකයන්ගෙන් ඉල්ලා ජනාධිපති මාධ්\u200dය අංශය සඳහන් කළේය දෙරට අතර ආයෝජන වාණිජ සම්බන්ධතා පුළුල් කිරීමේ අරමුණෙන් පැවති සාකච්ඡාවේදී ඩිජිටල් ආර්ථික සංචාරක පුනර්ජනනීය බලශක්ති තොරතුරු තාක්ෂණ ක්ෂේත්\u200dර පිළිබඳව විශේෂ අවධානය කෙරිණි අනුව දෙරට අතර වෙළෙඳ කටයුතු මුල්කර ගනිමින් ලංකාවේ ආයෝජන අවස්ථා පුළුල් කිරීම පිළිබඳව සාකච්ඡාවට මෙහිදී ලංකාවේ අයෝජන අවස්ථා කෙරෙහි වීමට ඉන්දීය පරිමාණ ව්\u200dයාපාරික නියෝජිතයන් කැමැත්ත අතර සඳහා අවශ්\u200dය ආයෝජන පහසුකම් සැපයීමට රජය එකඟ ඉන්දියාවේ ආරක්ෂාවට හානිදායක අයුරින් භූමිය ගැනීමට නොදෙන බවට ජනාධිපති අනුර කුමාර දිසානායක ඉන්දීය අග්\u200dරාමාත්\u200dය නරේන්ද්\u200dර පොරොන්දු ඉන්දීය අග්\u200dරමාත්\u200dයවරයා සමග දෙසැම්බර් වැනිදා ඒකාබද්ධ ප්\u200dරවෘත්ති සාකච්ඡාවකට එක්වෙමින් ජනාධිපතිවරයා සිටියේය ඉන්දියාවේ ආරක්ෂාවටත් කලාපයේ ස්ථාවරත්වයටත් හානිදායක කිසිදු ආකාරයකින් භූමිය ගැනීමට ලංකාව නොදෙන බවට ඉන්දියානු අග්\u200dරාමාත්\u200dයවරයාට පොරොන්දු සහතික ජනාධිපතිවරයා පැවසීය සිටියේ එළඹෙන් වසර ගණනාව තවදුරටත් ශක්තිමත් බවට කිසිදු සැකයක් ඉන්දියාව සමග සහයෝගීතාවය අඛණ්ඩව වර්ධනය කිරීම පුළුල් කිරීම කෙරෙහි ලංකාව විශාල වැදගත්කමක් නැවත අවධාරණය කරනවා එමෙන්ම ලංකාවේ සංචාරයක් සඳහා පැමිණෙන ලෙසට ඉන්දීය අග්\u200dරාමාත්\u200dය නරේන්ද්\u200dර මෝදිට ආරාධනා ජනාධිපති අනුර කුමාර දිසානායක ප්\u200dරවෘත්ති සාකච්ඡාවේදී පැවසීය ජනාධිපති අනුර කුමාර දිසානායක පළමු විදෙස් සංචාරය ඉන්දියාව ගැනීම පිළිබඳව ඉන්දීය අගමැති නරේන්ද්\u200dර මෙහිදී සතුට කළේය ජනාධිපතිවරයා සමග සංහිඳියාව ප්\u200dරතිසංස්කරණය පිළිබඳව සාකච්ඡා පැවසූ ඉන්දීය අග්\u200dරාමාත්\u200dයවරයා රජය දෙමළ ජාතීන්ගේ අභිලාෂයන් කරනු ඇතැයි විශ්වාසය කළේය අද්විතීය ඩිජිටල් අනන්\u200dයතා වැඩසටහනක් සඳහා ලංකාව සමඟ ඉන්දියාව සහයෝගයෙන් කටයුතු කරන අගමැති මෙහිදී පැවසීය ලංකාවේ සංවර්ධනය සඳහා ඉන්දියාවේ ශක්තිමත් සහයෝගය ඉන්දීය අගමැතිවරයා ප්\u200dරකාශයේදී අවධාරණය කළේය සාම්පූර් සූර්ය බලශක්ති ව්\u200dයාපෘතිය ක්\u200dරියාත්මක කිරීමට පියවර ගැනීම ලංකාවේ අවශ්\u200dයතා අනුව ධාරිතාව තවදුරටත් කිරීම ඉන්දියාවෙන් ලංකාවට ස්වභාවික ද්\u200dරව සැපයීම ඉන්දියාව ලංකාව අතර ධාරිතා විදුලි අන්තර් සම්බන්ධතාවයක් ස්ථාපිත කිරීම සත්ත්ව වෘක්ෂලතා ඇතුළු පාරිසරික ආරක්ෂාවට ප්\u200dරමුඛත්වය දෙමින් සමුද්\u200dර සන්ධියේ අක්වෙරළ ශක්තිය ඒකාබද්ධව සංවර්ධනය කිරීම කරුණු ගැනද මෙහිදී ඉන්දීය අග්\u200dරාමාත්\u200dයවරයා ජනාධිපතිවරයා අතර සාකච්ජා පවත්වා ඉන්දීය විදේශ කට

In [ ]:


stopwords = {
    "අද", "අප", "අපි", "අපේ", "අතර", "අනුව", "අය", "අයගේ", "ඇත", "ඇති", "ඇතුළු",
    "ඒ", "එම", "එය", "එහි", "එක්", "එක", "එකක්", "කර", "කරන", "කරයි", "කරමින්",
    "කළ", "කිරීම", "කියන", "කියා", "ගැන", "ගැනීමට", "ගැනීම", "තම", "තුළ", "ද", "දී",
    "දක්වා", "දැයි", "නම්", "නමුත්", "නිසා", "බව", "බවට", "බවයි", "බවද", "මත", "මෙන්",
    "මෙම", "මේ", "ය", "යන", "ලෙස", "වූ", "වෙත", "වෙනුවෙන්", "සහ", "සිට", "සඳහා",
    "හා", "හෝ", "මගින්", "බවත්"
}



stopwords = sorted(stopwords)

print(f"Stopwords: {len(stopwords)}")

Stopwords: 57

In [15]:
# Embed documents with BGE-M3
from sentence_transformers import SentenceTransformer
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
embedding_model_name = "BAAI/bge-m3"
embedding_model = SentenceTransformer(embedding_model_name, device=device)

embeddings = embedding_model.encode(
    documents,
    batch_size=16,
    show_progress_bar=True,
    normalize_embeddings=True,
)

print(embeddings.shape)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/54.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/687 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/2.27G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/444 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/964 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

Batches:   0%|          | 0/125 [00:00<?, ?it/s]

(1999, 1024)

In [ ]:
# Configure BERTopic with UMAP, HDBSCAN, and CountVectorizer
from bertopic import BERTopic
from hdbscan import HDBSCAN
from sklearn.feature_extraction.text import CountVectorizer
from umap import UMAP

umap_model = UMAP(
    n_neighbors=3,
    n_components=5,
    min_dist=0.0,
    metric="cosine",
    random_state=SEED,
)

hdbscan_model = HDBSCAN(
    min_cluster_size=2,
    min_samples=1,
    metric="euclidean",
    cluster_selection_method="leaf",
    prediction_data=True,
)

vectorizer_model = CountVectorizer(
    stop_words=list(stopwords),
    token_pattern=r"(?u)\b\w\w+\b",
    ngram_range=(1, 2),
    min_df=1,
)

topic_model = BERTopic(
    embedding_model=embedding_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer_model,
    language="multilingual",
    calculate_probabilities=True,
    verbose=True,
)

In [56]:
# Fit BERTopic using the precomputed BGE-M3 embeddings
topics, probabilities = topic_model.fit_transform(documents, embeddings)

df["topic_id"] = topics
df["topic_probability"] = [float(np.max(row)) if row is not None and len(row) else np.nan for row in probabilities]

topic_info = topic_model.get_topic_info()
topic_info.head(20)

2026-08-10 15:49:03,361 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm

2026-08-10 15:49:11,729 - BERTopic - Dimensionality - Completed ✓
2026-08-10 15:49:11,730 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-08-10 15:49:11,843 - BERTopic - Cluster - Completed ✓
2026-08-10 15:49:11,848 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-08-10 15:49:13,383 - BERTopic - Representation - Completed ✓

TypeError: object of type 'numpy.float64' has no len()

In [51]:
# Cluster/topic summary
print(df["topic_id"].value_counts().head(20))
print("Noise articles:", int((df["topic_id"] == -1).sum()))
print("Number of topics found:", df["topic_id"].nunique() - (1 if -1 in df["topic_id"].values else 0))

topic_info.head(30)

topic_id
-1     343
 0      17
 1      13
 2      13
 3      12
 4      12
 5      12
 6      12
 7      12
 8      12
 9      11
 10     11
 11     11
 12     11
 13     11
 14     11
 15     11
 16     11
 17     10
 18     10
Name: count, dtype: int64
Noise articles: 343
Number of topics found: 276

,Topic,Count,Name,Representation,Representative_Docs
0,-1,343,-1_වන_සම_නව_යල,"[වන, සම, නව, යල, ලක, මට, පත, අන, හන, වත]",[ඉදිරි ජනාධිපතිවරණයේදී ඡන්දදායකයින් ලක්ෂ 7කට ඡ...
1,0,17,0_මන වර_මන_වරප_වරප රස,"[මන වර, මන, වරප, වරප රස, මන වරය, පක කත, පනත, අ...",[පක්ෂ විනය කඩ කිරීම නිසා අධිකරණ නියෝග වලින් මන...
2,1,13,1_පනත_පනත පත_බල පනත_අඟ,"[පනත, පනත පත, බල පනත, අඟ, බල, twitter, බලශක, අ...",[ශ්‍රී ලංකාව ඉන්දියාවේ කොටසක් ද? :'හරින් ඇමතික...
3,2,13,2_ඉර_ඉර නය_ජනපදය_සත ජනපදය,"[ඉර, ඉර නය, ජනපදය, සත ජනපදය, සම සන, ඇම, කච, නල...",[ඇතැම් නැව් ආරක්ෂිතව ගමන් කරවීමට චීනය හා ඉරානය...
4,3,12,3_ඩකය_කට_තරග_කට ආයතනය,"[ඩකය, කට, තරග, කට ආයතනය, තරග වල, කණ, ටර වන, කණ...",[Fox Hill අනතුර: සාමාන්‍ය මාර්ග නීති මෝටර් රථ ...
5,4,12,4_ජනත රම_ආර ගම_ඊශ යල_ඇම,"[ජනත රම, ආර ගම, ඊශ යල, ඇම, යල කය, ඊශ, භය ජපක, ...",[ආරුගම්බේ ආරක්ෂක තර්ජනය ගැන ඇමති හෙළි කළ කරුණු...
6,5,12,5_නවකත_වන දය_චර_දය,"[නවකත, වන දය, චර, දය, නවකත වක, යනව, පටන, ශල, ත...",[මම ලියන හැටි' : රූපා ශ්‍රියානි ඒකනායක. ශ්‍රිය...
7,6,12,6_තනය_ආය ධයක_ගලය_බළ,"[තනය, ආය ධයක, ගලය, බළ, වසක, පහරද තනය, කකර, පහර...",[තියුණු ආයුධයකින් පහරදී පුද්ගලයෙකු ඝාතනය කරයි....
8,7,12,7_වන හම_කසන_කන කසන_කට යක,"[වන හම, කසන, කන කසන, කට යක, කසන රය, යක වන, ඉන,...",[ආධාර රැගත් තවත් යානයක් කටුනායකට. ලාංකික ජනතාව...
9,8,12,8_නද_cctv_නද උත_ගලය,"[නද, cctv, නද උත, ගලය, පහරද, වන සර, හලට, හලට ළ...",[වනාතේ බිම්සරට එල්ල වූ වෙඩිල්ල. බොරැල්ලේ පිහිට...
10,9,11,9_කසළ_එකත_අපද රව_පර සර,"[කසළ, එකත, අපද රව, පර සර, අපද, යටව, කසළ රම, සර...",[ගම්පහ තැනින් තැන යටවේ. කිහිපයක හැලෙන ධාරානිපා...
11,10,11,10_කම වන_කම_සම ගම_සට දනය,"[කම වන, කම, සම ගම, සට දනය, රජය, ගම, වත කම, කම ...",[වතු කම්කරුවන් ගැන කම්කරු විනිශ්චය සභාව දුන් න...
12,11,11,11_මහජන උපය_උපය සම_මහජන_උපය,"[මහජන උපය, උපය සම, මහජන, උපය, බල මණ, මණ ඩලය, ඩ...",[විදුලි ගාස්තු ඉහළ දැමීමේ තීරණය 15වැනිදා. විදු...
13,12,11,12_වහන_අපවත_උයන_ඩක වක,"[වහන, අපවත, උයන, ඩක වක, සනය, වහන නමක, ඩක, නමක,...",[නා උයන ආරණ්‍ය සේනාසනයේ අනතුරක් - භික්ෂූන් වහ...
14,13,11,13_ටල_ටල ආර_සය බර_පද ධත,"[ටල, ටල ආර, සය බර, පද ධත, ආර, 2026, ආද යම, දත,...",[‘Visa ශ්‍රී ලංකා සයිබර් ආරක්ෂණ සමුළුව 2026’ ස...
15,14,11,14_දහස පක_පක ෂය_ජයද_ජයද ජපක,"[දහස පක, පක ෂය, ජයද, ජයද ජපක, පක, දහස, ෂය, රණ ...",[මෛත්‍රිපාල සිරිසේන: ශ්‍රී ලංකා නිදහස් පක්ෂ සභ...
16,15,11,15_රඹ_තහනම_අධ දන_අම රඹ,"[රඹ, තහනම, අධ දන, අම රඹ, අල ලස, ටප අම, ළඹ මහ, ...",[කෙහෙළියට එරෙහි තවත් නඩුවක් ඔක්තෝබර් සිට විභාග...
17,16,11,16_සත ජනපද_ජනපද_ජක_ළඹ වර,"[සත ජනපද, ජනපද, ජක, ළඹ වර, ෂක බළක, හව, ඇම, හම,...",[ශ්‍රී ලංකාවට පැමිණෙන ඈන් රාජකීය කුමරිය කවුද?....
18,17,10,17_කකර_අඩ වට_අත අඩ_ශර,"[කකර, අඩ වට, අත අඩ, ශර, අඩ, රද ශය, අව, වලස, බණ...",[වසර ගණනකට පසුව හෙළිවූ තිදරු මවගේ අභිරහස. ගාල්...
19,18,10,18_අයව_බඳවද_කච_ජන,"[අයව, බඳවද, කච, ජන, අධ පන, රත දන, ජන පත, 2026,...",[සියලු මන්ත්‍රීවරුන්ට අධ්‍යාපන ප්‍රතිසංස්කරණ ග...
20,19,10,19_කල බද_හන_ගමන ෂන_රව හන,"[කල බද, හන, ගමන ෂන, රව හන, හනය, තහඩ, බද, ගමන ග...",[සැප වාහන හොරෙන් ලියාපදිංචි කළ හැටි එළියට. මෝට...
21,20,10,20_රක ෂණ_ෂණ වරණය_රක රක_එන නත,"[රක ෂණ, ෂණ වරණය, රක රක, එන නත, රත ශක, ශක කරණ, ...",[යුනිසෙෆ් ප්‍රතිශක්තිකරණ එන්නත් ලංකාවට. 2026 ...
22,21,10,21_මර ෂල_ෂල_ඩසටහන_හව,"[මර ෂල, ෂල, ඩසටහන, හව, කළමන, හව වන, ලණ, රසර, ළ...",[තිරසාර ව්‍යාපාරික පරිවර්තනයට කොමර්ෂල් හි Forw...
23,22,10,22_ආහ_උපප_එන_ලන ලම,"[ආහ, උපප, එන, ලන ලම, බල මණ, ආපන, වනය, මහ ලන, ආ...",[ආසියානු සංවර්ධන බැංකුවෙන් ලංවීමට ඩොලර් මිලියන...
24,23,10,23_වනඅල_අල_පහරද_අල යක,"[වනඅල, අල, පහරද, අල යක, බකම, වනජ, අධ ගයට, වනජ ...",[වල් අලි පහරින් පියා-දුව අනූ නවයෙන් බේරෙති. ප...
25,24,10,24_වන දල_ලන ජයවර_අධ කරණය_කරණය,"[වන දල, ලන ජයවර, අධ කරණය, කරණය, මඩ, ටප, ජයවර, ...",[මෛත්‍රීපාල සිරිසේන: වැඩිම වාර ගණනක් ව්‍යවස්ථා...
26,25,10,25_ජප_හම වක_අන යක_යක මහත,"[ජප, හම වක, අන යක, යක මහත, මහත, පත අන, කච, සත ...",[අනුර හා ජපාන විදේශ රාජ්‍ය ඇමති අතර හමුවක්. ජප...
27,26,10,26_බලපත_බද මස_බද_දන සම,"[බලපත, බද මස, බද, දන සම, සම ගම, අයකර, මස ජනර, ...",[බාර් ලයිසන් වැරදි ක්‍රමයට පිනට දීලා නැහැ - රන...
28,27,10,27_ඉසව_පදක_මලල_පදක කම,"[ඉසව, පදක, මලල, පදක කම, තරග, තරග වල, ටර 100, ඔ...",[දකුණු ආසියාවේ වේගවත් ම ක්‍රීඩකයා සහ ක්‍රීඩිකා...
29,28,10,28_කකර_වසන_රථය_අඩ වට,"[කකර, වසන, රථය, අඩ වට, අත අඩ, කකර වන, අපර, අත,...",[අතුරුගිරියේ ඝාතකයන් පළා ගිය බස් රථය කතරගමින් ...

In [52]:
# Inspect sample titles per topic
for topic_id, group in df[df["topic_id"] != -1].groupby("topic_id"):
    print(f"=== Topic {topic_id} ({len(group)} articles) ===")
    for title in group["title"].head(10):
        print(f"- {title}")
    print()

    if topic_id >= 10:
        break

=== Topic 0 (17 articles) ===
- මහනුවර නගර සභා මන්ත්‍රීන්ගේ දුරකතන දීමනාව අවලංගුයි
- තවත් කලු සුද්දෝ පාර්ලිමේන්තුවේ ඉන්නවා
- මහ බැංකුවේ අත්තනෝමතික වැටුප් වැඩි කර ගැනීම අවලංගු කිරීමේ පනත පාර්ලිමේන්තුවට
- ධීවර විශ්‍රාම වැටුප යථාර්ථයක් වෙන හැඩ
- පාර්ලිමේන්තු විශ්‍රාම වැටුප් පනත ඉවත් කිරීමට කැබිනට් අනුමැතිය
- මන්ත්‍රී විශ්‍රාම වැටුප ඉවත් කරන පනත් කෙටුම්පත පාර්ලිමේන්තුවට: 400කට වැඩි ප්‍රතිලාභීන්ට සිදුවන්නේ කුමක් ද?
- අමාත්‍යවරයෙකුගේ මන්ත්‍රී ධුරය බල රහිත කරන ලෙස ඉල්ලා අභියාචනාධිකරණයට පෙත්සමක්
- පැන්ෂන් කැපුවොත් නඩු දානවා
- මන්ත්‍රීවරුන්ට ගිනිඅවි දීම: ආණ්ඩුව සැරසෙන්නේ 'මොකක් හරි සෙල්ලමකට' ද?
- මන්ත්‍රී පුටුවක් හිස්: මහ ලේකම් මැකෝට  දන්වයි

=== Topic 1 (13 articles) ===
- මතභේදයට තුඩු දී ඇති විදුලිබල පනත් කෙටුම්පත ආණ්ඩුක්‍රම ව්‍යවස්ථාවට පටහැනි වන්නේ කෙසේද ?
- පාර්ලිමේන්තු මන්ත්‍රීවරුන්ට පෙර වාහන පර්මිට් හිමිවූ රාජ්‍ය නිලධාරින් කවුද ?
- රියදුරු බලපත්‍ර එක් දින සේවාව පිටපළාත්වලටත්
- විදුලිබල පනත් කෙටුම්පත සම්මතයි: දැන් සිදුවන්නේ කුමක් ද?
- ගල් අඟුරු ටෙන්ඩරයෙන්  දූෂණයකට  පාර කැපිලා
- විදුලියේ වර්ජකයන්ට ජනපතිගෙන් රතු එළියක්
- Ather 450X  ඉලෙක්ට්‍රික් යතුරුපැදිය  වෙළෙඳ පොළට
- ඉන්දියාව එක්ක අත්සන් තැබූ ගිවිසුමේ පිටපතක් දෙන්න
- රියදුරු බලපත්‍රය පූර්ණ ශ්‍රවණාබාධිතයින්ටත්
- ශ්‍රී ලංකාව ඉන්දියාවේ කොටසක් ද? :'හරින් ඇමතිකමෙන් නෙරපිය යුතුයි'

=== Topic 2 (13 articles) ===
- ඇතැම් නැව් ආරක්ෂිතව ගමන් කරවීමට චීනය හා ඉරානය අතර  සාකච්ඡා
- ඉරාන ප්‍රහාරය ට්‍රම්ප් යළිත් පස්සට ගනියි
- ඇෆ්ගනිස්තානයේ බාග්‍රම් ගුවන් කඳවුර ට්‍රම්ප් යළි ඉල්ලයි
- ඉරානය න්‍යෂ්ටික අවියක් තබා නොගැනීමට එකඟවුණා
- තෙල් බැරලය ඩොලර් 100න් පහළට
- බොරතෙල් මිල ඉහළට
- ඇමෙරිකාවේ ඉල්ලීම් සාම සාකච්ඡා අසාර්ථකවීමට හේතුවයි
- ඇමෙරිකාව සමග සාකච්ඡාවල ප්‍රගතියක් තියෙනවා -ඉරානය
- ඇමෙරිකාව ඉරාන බෝට්ටුවලට පහරදෙද්දි ඉරානය එමීරයේ තෙල් පහසුකමකට පහර දෙයි
- බ්‍රිතාන්‍යයේ සිටින සරණාගතයින්ට සහනයක්

=== Topic 3 (12 articles) ===
- ලෝක කුසලානය අතරේ ක්‍රිකට් තරු දෙකක් විවාහ ගිවිස ගනිති
- ශ්‍රී ලංකාව වෙනුවෙන් පකිස්ථාන පාර්ලිමේන්තුවට යෝජනාවක්: ක්‍රීඩකයින්ට 'රාජ්‍ය නායක ආරක්ෂාව' ලැබෙන්නේ මෙහෙමයි
- Fox Hill ධාවන ශූරයෙක් වූ බුද්ධික ගැන සංවේදී කතාවක්
- සචිත්‍ර ගේ කටහඬ පරීක්ෂණ වාර්තාව පමා වෙයි
- දියතලාව බිහිසුණු ඛේදවාචකයේ නොදත් කතාව
- Lanka T10: අත්අඩංගුවට පත් ගෝල් මාවල්ස් හිමිකරුගෙන් අධිකරණයට රහස් ප්‍රකාශයක්
- ලෝක කුසලානය අතරේ ක්‍රිකට් තරුදෙකක් ගල්කිස්ස හෝටලයේදි අතිනත ගනිති
- පකිස්ථාන - ශ්‍රී ලංකා ක්‍රිකට් තරගාවලියේ අලුත් ම තත්ත්වය
- Fox Hill අනතුර: සාමාන්‍ය මාර්ග නීති මෝටර් රථ ධාවන තරගයකටත් අදාළ කර ගත හැකි ද?
- මෙසීව හරි හැටි බලන්න බැරි වුණැයි කලහයක්

=== Topic 4 (12 articles) ===
- ඊශ්‍රායල ජාතිකයින් විසින් සිදුකරන ඉදිකිරීම්වලට අවසර දීලා නැහැ - අගමැති
- ආරුගම්බේ ආරක්ෂක තර්ජනය ගැන ඇමති හෙළි කළ කරුණු
- ශ්‍රී ලංකාවේ රුසියානු තානාපති දුන් පොරොන්දුව
- කැප්පෙටිපොළලා- දොන් ජුවන් ධර්මපාලලා එකතු වෙලා
- සන්නද්ධ තරුණ නැගිටීමක සිට විධායකය දක්වා: JVP සිට NPP දක්වා පැමිණි ගමන්මග
- ජනාධිපතිවරණය 2024: ශ්‍රී ලංකාවේ අනාගතය කලාපීය බලවතුන් අතර දෝලනය වෙයි ද?
- දඹුල්ලේ විදෙස් සංචාරකයෝ පිරිලා , ආරක්ෂාව තර කරයි
- ආරුගම්බේ තර්ජනය සම්බන්ධයෙන් අප මෙතෙක් දන්නේ මොනවා ද?
- යාපනයේ හැර දිවයිනේ ඕනෑම අධිකරණයක සාක්ෂි දීමට සූදානම් බව ගෝඨාභය කියයි
- ලලිත් - කුගන් සිද්ධියට සාක්ෂි දීමට ගෝඨා සූදානම්

=== Topic 5 (12 articles) ===
- මම ලියන හැටි' : නිශ්ශංක විජේමාන්න
- මම ලියන හැටි': ආරියවංශ අබේසේකර
- මම ලියන හැටි': අනුරසිරි හෙට්ටිගේ
- මම ලියන හැටි': දර්ශනා ශම්මි විජේතිලක
- පොප්සිකල් කෝටුවකින් ඩොලර් උල්පතකට මග පාදා ගත් ගුවන් යානා ආකෘති නිර්මාණකරුවා
- මම ලියන හැටි' : රූපා ශ්‍රියානි ඒකනායක
- දැන් පොත්වල ආනන්දයත් නෑ... ප්‍රඥාවත් නෑ...
- සුමනා ජයතිලක: 'හඳ නැන්දා' නිහඬ වෙයි
- මම ලියන හැටි' : චන්දි කොඩිකාර
- මම ලියන හැටි' : සමන් වික්‍රමාරච්චි

=== Topic 6 (12 articles) ===
- ස්ථාන දෙකකදී ඝාතන දෙකක්
- මව හා පුතා ඝාතනය කරලා
- වැලිපැන්න යුද පිටියක් කළ ආපන ශාලාවේ ගැටුම
- පුතු නිවසේ නැති අතරේ මවට අත්වූ ඉරණම
- තියුණු ආයුධයකින් පහරදී පුද්ගලයෙකු ඝාතනය කරයි
- බිරිය හා තවත් අයෙක් සමග මත්පැන් බීමෙන් පසු ඔහුව ඝාතනය කලේ කවුද ?
- ප්‍රදේශ කිහිපයකින් වාර්තා වූ ඝාතන
- පොල් වත්තේදී ඝාතනයවූ තරුණයා මරණ පරීක්ෂණයේදී කාන්තාවක් වෙයි
- යුවළක් කපා කොටා මරලා
- බිරිඳ ව ඝාතනය කළ නරුම සැමියා සියල්ල වමාරයි

=== Topic 7 (12 articles) ===
- ඉන්දු - ශ්‍රී ලංකා මගී යාත්‍රා සේවය සිකුරාදා සිට
- මධ්‍යම අප්‍රිකානු සෙබළුන් 14ක් බේරාගත් ලංකා ගුවන් හමුදා මෙහෙයුම
- ඉන්දියාවෙන් ගලවා ගැනීමේ කණ්ඩායමක් පැමිණේ
- ආපදාවට සහන සලසන්න ඇමෙරිකා යානා දෙකක් එයි
- මඩකලපුව වෙරළට ඉන්දීය ජාතික ධජය සහිත යානයක කොටසක් ගොඩ ගසයි
- අරාබි භූමි මෙහෙයුම් නිමාවට
- අරාබියේ විශාලතම ගුවන් යානා දෙක ආධාර රැගෙන මෙරටට
- ආධාර රැගත් තවත් යානයක් කටුනායකට
- කන්කසන්තුරේ සිට නැවෙන් ඉන්දියාවට යන්න අවශ්‍ය දෑ මොනවා ද?
- දූපතක සිරවී සිටි රෝගීන් පිරිසක් ගුවනින් යාපනය රෝහලට

=== Topic 8 (12 articles) ===
- හමුදා සෙබළා වෙඩි වැදී රෝහලේ
- බීමත් රෝගීයා හෙදියකට පහරදී රෝහලෙන් පලායයි
- කොස්ගම වෙඩිතැබීමක්
- ජනේලයෙන් වෙඩි තබා ගිය වෙඩික්කරුගේ ඉලක්කය වරදී
- පැරණි පොලිස් මූලස්ථානයේ තිබූ CCTV කැමරා 7ක් අතුරුදන්
- ගල්කිස්ස බඩෝවිට වෙඩිතැබීමක්
- වනාතේ බිම්සරට එල්ල වූ වෙඩිල්ල
- සංගීත ප්‍රසංගයකදී ගායන ශිල්පී නදිමාල්ට පහරදුන් අයෙකු අත්අත්අඩංගුවට
- බොරැල්ල කැලඹූ වෙඩි වරුසාව ගැන තවත් තොරතුරු රැසක්
- පුද්ගලයෙක් ඇතුගලින් ඇදවැටෙයි

=== Topic 9 (11 articles) ===
- ගම්පහ තැනින් තැන යටවේ
- ආපදාවෙන් පසු පැමිණි ආපදාවක්': ටොන් දස දහස් ගණනක කසළ කඳුවලට විසඳුම කුමක් ද?
- මහනුවර යට වෙන්න හේතුව කිරිඇල්ල කියයි
- අම්මා කෙනෙක් මාස 8ක දරුවා තුරුළු කරගෙන මියගොස් සිටියා': නායයාම් මැද සිදුවූ සෝචනීය කතා
- කෑ ගහනවා ඇහුණා, ඊට පස්සේ අපි පීනගෙන ගියා, එතකොට ආච්චි කෙනෙක් අලලන් තව ආච්චි කෙනෙක් ඉන්නවා, එයා මැරිලා'
- ගම්පහ පිරිසිදු කරයි
- ගංවතුර මැද චෛත්‍යයේ කොතේ එල්ලී සිටි නායක හිමි
- කොළඹ පැති තවමත් යටවෙලා
- අවදානම් නොතකා සිය අසල්වැසියන් සොයා වෙහෙසෙන ගම්වාසීන්: 'මේ ළමයව පැයකට ඉස්සෙල්ලා බේර ගන්න තිබ්බා'
- මම ලණු ටිකක් හොයා ගත්තා ඔක්කොලාම එකට ගැට ගහන්න, ගහගෙන ගියොත් අපි 29 දෙනාම එකට මැරෙමු කියලා තමයි අපි කතා වුණේ.'

=== Topic 10 (11 articles) ===
- වතු කම්කරු වැටුප: ගැසට් නිවේදනය ක්‍රියාත්මක කිරීම වළක්වාලමින් ශ්‍රේෂ්ඨාධිකරණයෙන් අතුරු තහනම් නියෝගයක්
- චිචීගේ රොකට් එක ගැන අගමැතිනියගේ හෙළිදරව්ව
- වතු කම්කරුවන් ගැන කම්කරු විනිශ්චය සභාව දුන් නිර්දේශ ක්‍රියාත්මක වෙයි ද ?
- ටොයෝටා සමාගමෙන් පෙරළියක්
- වතු කම්කරු වැටුප ඉහළ දැමූ ගැසට් නිවේදනය යථාර්ථයක් වෙයි ද?
- වතු සමාගම්වල කම්කරුවන්ට රජයෙන් දීමනාවක් ගෙවීම නිවැරදි තීරණයක් ද?
- ජපානයේ සේවකයින්ට ලොකු වැටුප් වර්ධකයක්
- ’වත්ත’ ’නිදහස් ගම්මාන’ ලෙස වෙනස් කරයි
- වතු කම්කරු වැටුප් වැඩි කිරීමට එරෙහි පෙත්සම විභාගයට
- රනිල් සහ හරිනි අතර වාග් සටන පිටුපස කතාව

In [20]:
# Save article-level assignments and topic summaries
assignments_path = RESULTS_DIR / "bge_m3_bertopic_assignments.csv"
topics_path = RESULTS_DIR / "bge_m3_bertopic_topics.csv"

df.drop(columns=["document"], errors="ignore").to_csv(assignments_path, index=False, encoding="utf-8-sig")
topic_info.to_csv(topics_path, index=False, encoding="utf-8-sig")

print(f"Saved assignments: {assignments_path.resolve()}")
print(f"Saved topics: {topics_path.resolve()}")

Saved assignments: /kaggle/working/results/bge_m3_bertopic/bge_m3_bertopic_assignments.csv
Saved topics: /kaggle/working/results/bge_m3_bertopic/bge_m3_bertopic_topics.csv

In [21]:
# Optional BERTopic visualizations
# These are useful in Jupyter/Colab but can be slow for large corpora.

# topic_model.visualize_topics()
# topic_model.visualize_barchart(top_n_topics=20)
# topic_model.visualize_hierarchy()